import {
  FileSignature,
  UserCheck,
  Stamp,
  BookOpen,
  Contact,
  Banknote,
  ReceiptText,
  Receipt,
  Wallet,
  Award,
  ShieldCheck,
  Heart,
  FileCheck2,
} from 'lucide-react';

export const DOCUMENT_GENERATORS = [
  {
    id: 'agreement',
    title: 'Employment Agreement',
    bnTitle: '',
    category: 'contracts',
    categoryLabel: 'Contracts & Legal',
    description: 'Bilingual (Bangla & English) standard overseas and agency employment legal contract.',
    bnDescription: '',
    icon: FileSignature,
    color: 'from-blue-600 to-indigo-600',
    badge: 'Legal Contract',
    badgeStyle: 'bg-blue-50 text-blue-700 dark:bg-blue-950/50 dark:text-blue-300 border-blue-200 dark:border-blue-800',
  },
  {
    id: 'client-form',
    title: 'Client & Guardian Form',
    bnTitle: '',
    category: 'contracts',
    categoryLabel: 'Contracts & Forms',
    description: 'Applicant profile, guardian guarantee, emergency contacts and legal declaration.',
    bnDescription: '',
    icon: UserCheck,
    color: 'from-sky-600 to-cyan-600',
    badge: 'Application Form',
    badgeStyle: 'bg-sky-50 text-sky-700 dark:bg-sky-950/50 dark:text-sky-300 border-sky-200 dark:border-sky-800',
  },
  {
    id: 'indian-visa',
    title: 'Indian Visa Submission File',
    bnTitle: '',
    category: 'contracts',
    categoryLabel: 'Visa & Passport',
    description: 'Applicant profile, port details, appointment tracking and submission slip.',
    bnDescription: '',
    icon: Stamp,
    color: 'from-amber-600 to-orange-600',
    badge: 'Visa File',
    badgeStyle: 'bg-amber-50 text-amber-700 dark:bg-amber-950/50 dark:text-amber-300 border-amber-200 dark:border-amber-800',
  },
  {
    id: 'passport-sub',
    title: 'Passport Submission Slip',
    bnTitle: '',
    category: 'contracts',
    categoryLabel: 'Visa & Passport',
    description: 'Passport custody handover voucher with barcode and tracking identifier.',
    bnDescription: '',
    icon: BookOpen,
    color: 'from-emerald-600 to-teal-600',
    badge: 'Custody Slip',
    badgeStyle: 'bg-emerald-50 text-emerald-700 dark:bg-emerald-950/50 dark:text-emerald-300 border-emerald-200 dark:border-emerald-800',
  },
  {
    id: 'job-verification',
    title: 'Job Verification Form',
    bnTitle: '',
    category: 'contracts',
    categoryLabel: 'Verification & Jobs',
    description: 'Company, Client & Job Verification Details Form for overseas employment and stay.',
    bnDescription: '',
    icon: FileCheck2,
    color: 'from-blue-600 to-cyan-600',
    badge: 'Verification Form',
    badgeStyle: 'bg-cyan-50 text-cyan-700 dark:bg-cyan-950/50 dark:text-cyan-300 border-cyan-200 dark:border-cyan-800',
  },
  {
    id: 'idcard',
    title: 'Employee ID Card',
    bnTitle: '',
    category: 'hr',
    categoryLabel: 'HR & Identity',
    description: 'Front and back official corporate employee identity card with QR and blood group.',
    bnDescription: '',
    icon: Contact,
    color: 'from-indigo-600 to-purple-600',
    badge: 'Identity Card',
    badgeStyle: 'bg-indigo-50 text-indigo-700 dark:bg-indigo-950/50 dark:text-indigo-300 border-indigo-200 dark:border-indigo-800',
  },
  {
    id: 'payroll',
    title: 'Monthly Salary Slip',
    bnTitle: '',
    category: 'hr',
    categoryLabel: 'HR & Payroll',
    description: 'Complete breakdown of earnings, allowances, deductions, attendance and net salary.',
    bnDescription: '',
    icon: Banknote,
    color: 'from-teal-600 to-emerald-600',
    badge: 'Payroll Slip',
    badgeStyle: 'bg-teal-50 text-teal-700 dark:bg-teal-950/50 dark:text-teal-300 border-teal-200 dark:border-teal-800',
  },
  {
    id: 'invoice',
    title: 'Invoice Billing',
    bnTitle: '',
    category: 'accounts',
    categoryLabel: 'Accounts & Billing',
    description: 'Professional client invoice with itemized charges, VAT, tax and payment status.',
    bnDescription: '',
    icon: ReceiptText,
    color: 'from-violet-600 to-purple-600',
    badge: 'Tax Invoice',
    badgeStyle: 'bg-violet-50 text-violet-700 dark:bg-violet-950/50 dark:text-violet-300 border-violet-200 dark:border-violet-800',
  },
  {
    id: 'money-receipt',
    title: 'Money Receipt Voucher',
    bnTitle: '',
    category: 'accounts',
    categoryLabel: 'Accounts & Receipts',
    description: 'Official payment receipt voucher with amount in words, method and signatures.',
    bnDescription: '',
    icon: Receipt,
    color: 'from-blue-600 to-cyan-600',
    badge: 'Official Receipt',
    badgeStyle: 'bg-blue-50 text-blue-700 dark:bg-blue-950/50 dark:text-blue-300 border-blue-200 dark:border-blue-800',
  },
  {
    id: 'cash-voucher',
    title: 'Cash Money Voucher',
    bnTitle: '',
    category: 'accounts',
    categoryLabel: 'Accounts & Vouchers',
    description: 'Office cash disbursement and petty cash debit/credit expense voucher.',
    bnDescription: '',
    icon: Wallet,
    color: 'from-cyan-600 to-blue-600',
    badge: 'Cash Voucher',
    badgeStyle: 'bg-cyan-50 text-cyan-700 dark:bg-cyan-950/50 dark:text-cyan-300 border-cyan-200 dark:border-cyan-800',
  },
  {
    id: 'experience-certificate',
    title: 'Experience Certificate',
    bnTitle: '',
    category: 'certificates',
    categoryLabel: 'Certificates',
    description: 'Official corporate work experience and service release certificate letter.',
    bnDescription: '',
    icon: Award,
    color: 'from-rose-600 to-pink-600',
    badge: 'Certificate',
    badgeStyle: 'bg-rose-50 text-rose-700 dark:bg-rose-950/50 dark:text-rose-300 border-rose-200 dark:border-rose-800',
  },
  {
    id: 'character-certificate',
    title: 'Character Certificate',
    bnTitle: '',
    category: 'certificates',
    categoryLabel: 'Certificates',
    description: 'Formal character, conduct and moral standing testimonial certificate.',
    bnDescription: '',
    icon: ShieldCheck,
    color: 'from-emerald-600 to-green-600',
    badge: 'Certificate',
    badgeStyle: 'bg-emerald-50 text-emerald-700 dark:bg-emerald-950/50 dark:text-emerald-300 border-emerald-200 dark:border-emerald-800',
  },
  {
    id: 'marriage-certificate',
    title: 'Marriage Certificate',
    bnTitle: '',
    category: 'certificates',
    categoryLabel: 'Certificates',
    description: 'Official marital status verification certificate letter for embassy and visa.',
    bnDescription: '',
    icon: Heart,
    color: 'from-pink-600 to-rose-600',
    badge: 'Certificate',
    badgeStyle: 'bg-pink-50 text-pink-700 dark:bg-pink-950/50 dark:text-pink-300 border-pink-200 dark:border-pink-800',
  },
];

export const CATEGORIES = [
  { id: 'all', label: 'All Documents', bnLabel: '', count: 12 },
  { id: 'contracts', label: 'Contracts & Forms', bnLabel: '', count: 4 },
  { id: 'accounts', label: 'Accounts & Billing', bnLabel: '', count: 3 },
  { id: 'hr', label: 'HR & Payroll', bnLabel: '', count: 2 },
  { id: 'certificates', label: 'Certificates', bnLabel: '', count: 3 },
];

export const getGeneratorById = (id) => {
  if (!id) return null;
  return DOCUMENT_GENERATORS.find(
    (g) =>
      g.id === id ||
      (id === 'receipt' && g.id === 'money-receipt') ||
      (id === 'certificate-exp' && g.id === 'experience-certificate') ||
      (id === 'certificate-char' && g.id === 'character-certificate') ||
      (id === 'certificate-marr' && g.id === 'marriage-certificate')
  );
};
